"""Original geometric robot. MIT. No official Muse artwork is used."""
from pathlib import Path
import math,struct
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[1]
out=ROOT/'device/main/apps/muse/muse_avatar_public_frames.c'
atlas=Image.new('RGBA',(512,256))
frames=[]
for index in range(30):
 image=Image.new('RGBA',(64,64));draw=ImageDraw.Draw(image)
 mode='idle' if index<6 else 'connect' if index<10 else 'listen' if index<18 else 'think' if index<24 else 'happy' if index<28 else 'error'
 shift=round(math.sin(index*1.2))
 color='#FA9477' if mode=='error' else '#A3DFD4'
 dark='#193E47';light='#EFF9DC';accent='#FFD590'
 # Angular screen-headed robot, small rectangular torso and boots.
 draw.rectangle((27,7+shift,36,10+shift),fill=accent)
 draw.rectangle((30,10+shift,33,14+shift),fill=color)
 draw.rectangle((15,14+shift,48,40+shift),fill=dark)
 draw.rectangle((17,16+shift,46,38+shift),fill=color)
 draw.rectangle((21,20+shift,42,33+shift),fill=dark)
 if index==5:
  draw.rectangle((24,26+shift,28,27+shift),fill=light);draw.rectangle((35,26+shift,39,27+shift),fill=light)
 elif mode=='error':
  for x in (24,35):
   draw.line((x,23+shift,x+4,28+shift),fill=light,width=2);draw.line((x+4,23+shift,x,28+shift),fill=light,width=2)
 elif mode=='happy':
  for x in (24,35):draw.line((x,27+shift,x+2,24+shift,x+4,27+shift),fill=light,width=2)
 else:
  for x in (24,35):draw.rectangle((x,23+shift,x+3,29+shift),fill=light)
 draw.rectangle((27,35+shift,36,36+shift),fill=dark)
 draw.rectangle((21,41+shift,42,52+shift),fill=dark)
 draw.rectangle((23,43+shift,40,50+shift),fill=color)
 draw.rectangle((26,54+shift,29,57+shift),fill=color);draw.rectangle((34,54+shift,37,57+shift),fill=color)
 arm_y=29 if mode in ('listen','happy') else 44
 draw.rectangle((9,arm_y+shift,13,arm_y+8+shift),fill=color);draw.rectangle((50,arm_y+shift,54,arm_y+8+shift),fill=color)
 if mode=='listen':
  band=(index-10)//2
  for n in range(band+1):
   y=28+n*4;draw.rectangle((3,y,5,y+1),fill=accent);draw.rectangle((58,y,60,y+1),fill=accent)
 if mode in ('connect','think'):
  phase=(index-6)%4
  for n in range(4):draw.rectangle((12+n*12,3,14+n*12,5),fill=accent if n==phase else dark)
 if mode=='happy':
  draw.rectangle((6,13,8,15),fill=accent);draw.rectangle((55,8,57,10),fill=accent)
 if mode=='error':draw.rectangle((56,18,57,26),fill=accent);draw.rectangle((56,29,57,30),fill=accent)
 values=[]
 for r,g,b,a in image.getdata():values.append(((r>>3)<<11)|((g>>2)<<5)|(b>>3) if a else 0)
 frames.append(values);atlas.paste(image,((index%8)*64,(index//8)*64))
body=['// Copyright (c) 2026 manchunx7-bit. MIT License.\n// Original geometric robot. Generated by tools/generate_avatar.py.\n#include "muse_avatar_frames.h"\n']
for index,values in enumerate(frames):
 body.append('static const uint16_t frame_%d[4096] = {\n'%index)
 body.extend(','.join('0x%04x'%v for v in values[start:start+32])+',\n' for start in range(0,4096,32));body.append('};\n')
body.append('const lv_image_dsc_t muse_avatar_frames[30] = {\n')
for index in range(30):body.append('{.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.flags=0,.w=64,.h=64,.stride=128},.data_size=8192,.data=(const uint8_t*)frame_%d},\n'%index)
body.append('};\n');out.write_text(''.join(body),encoding='utf-8')
(ROOT/'docs/images').mkdir(parents=True,exist_ok=True);atlas.save(ROOT/'docs/images/avatar-atlas.png')
print('Original avatar: 30 immutable 64x64 RGB565 frames generated')
